---
base_directory: /kafka-zookeeper-cluster

zookeeper_parameters: 
  - { name: zookeeper1, id: 1, ip: 10.30.1.1, ssh_port: 2211 }
  - { name: zookeeper2, id: 2, ip: 10.30.1.2, ssh_port: 2212 }
  # - { name: zookeeper3, id: 3, ip: 10.30.1.3, ssh_port: 2213 }
kafka_parameters:
  - { name: kafka1, id: 1, ip: 10.30.2.1, ssh_port: 2221, zookeeper_connect: "10.30.1.1:2181,10.30.1.2:2181" }
  # - { name: kafka2, id: 2, ip: 10.30.2.2, ssh_port: 2222 }
  # - { name: kafka3, id: 3, ip: 10.30.2.3, ssh_port: 2223 }