# tasks file for java8
---  
- name: Install add-apt-repository
  become: yes
  apt: 
    name: software-properties-common 
    state: latest

- name: add oracle java8 repository
  apt_repository: state=present repo=ppa:webupd8team/java
  notify: apt-get update

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: get JAVA_HOME path
  shell: "echo $JAVA_HOME"
  register: JAVA_HOME

- name: set JAVA_HOME=/usr/lib/jvm/java-8-oracle
  when: JAVA_HOME.stdout != ''
  command: "echo JAVA_HOME=\"/usr/lib/jvm/java-8-oracle\" >> /etc/environment"